language: r
matrix:
  include:
    - r: release
    - os: osx
    - r: oldrel
cache: packages
git:
  depth: false

install: 
  - R --slave -e "if (!('remotes' %in% .packages(T))) install.packages('remotes')";
script:
  # build
  - R --slave -e "remotes::install_local(getwd(), force = TRUE, , upgrade = TRUE)";
  # test
  - R --slave -e "remotes::install_deps(dependencies = 'Suggests')"; # at least include devtools, testthat, roxygen2
  - R --slave -e "devtools::test(); testthat::test_dir('tests/testthat/', reporter = 'fail')";   # devtools::test() loads all and report result, testthat::test_dir() exit no-zero when a test fails  

notifications:
  email: false
